#!/bin/bash
#!/bin/bash

# Configuration
UPDATE_INTERVAL=86400  # 1 day in seconds

FORMULA_PATH=$(brew --prefix)/Homebrew/Library/Taps/qcastel/homebrew-test-cli-release/Formula/mycliexample.rb

# Function to check if an update is needed
check_for_update() {
    # Get the timestamp of the last update for mycliexample formula file
    last_update=$(stat -f "%m" "$FORMULA_PATH")

    # Get the current timestamp
    current_time=$(date +%s)

    # Check if the update interval has passed
    if [ $((current_time - last_update)) -ge $UPDATE_INTERVAL ]; then
        echo "Checking for updates..."
        update_cli
    else
        echo "Skipping update check. Running existing mycliexample..."
    fi
}


# Function to perform the update check and upgrade if needed
update_cli() {
    # Update Homebrew package lists
    brew update

    # Check if there are any outdated packages, specifically your CLI
    if brew outdated mycliexample > /dev/null; then
        read -p "A new version of mycliexample is available. Do you want to update? (y/n): " answer

        if [ "$answer" == "y" ]; then
            echo "Updating mycliexample..."
            brew upgrade mycliexample
            echo "mycliexample has been updated."
        else
            echo "Skipping update. Running existing mycliexample..."
        fi
    else
        echo "mycliexample is up to date."
    fi
}

# Rest of your CLI script goes here
echo "Running mycliexample..."
# Your CLI logic follows...


# Get Homebrew installation directory
HOMEBREW_PREFIX=$(brew --prefix)

# Adjust paths based on Homebrew installation
LIB_PATH="$HOMEBREW_PREFIX/lib/mycliexample"
source $LIB_PATH/lib/testinglib.sh

echo "Welcome to the CLI released using gitops principal and published via github and brew"

# Display the help
help() (
    self=$(basename "$0")
    cat <<END_OF_HELP

$(echo 'Get the current version')
   $self version

END_OF_HELP
)

cmd=${1:-}; shift || true
case $cmd in
    version)
        echo "Current version:"
        cat $LIB_PATH/version.txt
    ;;
    h     ) help; exit 0 ;;
    -h    ) help; exit 0 ;;
    --h   ) help; exit 0 ;;
    help  ) help; exit 0 ;;
    -help ) help; exit 0 ;;
    --help) help; exit 0 ;;

    *)
        self=$(basename "$0")
        echo "unknown command \"$cmd\", type \"$self help\" for a list of available commands" >&2
        exit 1
        ;;
esac